import "./globals.css";
import Footer from "./Ui/Footer";
import Navbar from "./Ui/Navbar";

export const metadata = {
  title: "Gloriouz Wings",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-[#fdf8f5]"
      >
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
